squid: rgw/s3-tests: iam: remove invalid Bucket param from list_buckets()
> botocore.exceptions.ParamValidationError: Parameter validation failed:
> Unknown parameter in input: "Bucket", must be one of: MaxBuckets, ContinuationToken, Prefix, BucketRegion

Signed-off-by: Casey Bodley <cbodley@redhat.com>
(cherry picked from commit 41b7297e7af6c1c794c075249732ebd6d8845f98)

Conflicts:
	src/test/rgw/s3-tests/s3tests_boto3/functional/test_iam.py
 - Renamed

Assisted-by: Claude Opus 5 <noreply@anthropic.com>
Signed-off-by: Adam C. Emerson <aemerson@redhat.com>