mgr/smb: fix ceph smb show when a cluster has not associated shares
Fix an error condition in the `ceph smb show` command.  When the ceph
smb show command was run after creating a usersgroups and cluster
resource but no shares resources the following traceback was seen:

```
Error EINVAL: Traceback (most recent call last):
  File "/usr/share/ceph/mgr/mgr_module.py", line 1910, in
_handle_command
    return CLICommand.COMMANDS[cmd['prefix']].call(self, cmd, inbuf)
  File "/usr/share/ceph/mgr/mgr_module.py", line 507, in call
    return self.func(mgr, **kwargs)
  File "/usr/share/ceph/mgr/object_format.py", line 592, in
_format_response
    robj = f(*args, **kwargs)
  File "/usr/share/ceph/mgr/smb/module.py", line 258, in show
    resources = self._handler.matching_resources(resource_names)
  File "/usr/share/ceph/mgr/smb/handler.py", line 403, in
matching_resources
    return self._search_resources(matcher)
  File "/usr/share/ceph/mgr/smb/handler.py", line 414, in
_search_resources
    for share_id in cluster_shares[cluster_id]:
KeyError: 'smbcluster'
```

Fixes: a5cde6ebe940
Reported-by: Anoop C S <anoopcs@cryptolab.net>
Resolves: rhbz#2300005
Signed-off-by: John Mulligan <jmulligan@redhat.com>
(cherry picked from commit 2119fc9330941d4863fce97356b77acb7635d4b3)