client: clean up warnings in fscrypt
Fix warnings/errors in ceph API tests that are present in FSCrypt.cc

src/client/FSCrypt.cc:90:6: error: variable 'olen' set but not used [-Werror,-Wunused-but-set-variable]
   90 |         int olen = 0;
      |             ^
src/client/FSCrypt.cc:91:6: error: variable 'line' set but not used [-Werror,-Wunused-but-set-variable]
   91 |         int line = 0;
      |             ^
src/client/FSCrypt.cc:945:2: error: is this the way to do it? [-Werror,-W#warnings]
  945 | #warning is this the way to do it?

Resolves: ISCE-3051

Signed-off-by: Christopher Hoffman <choffman@redhat.com>
(cherry picked from commit 12967a06121b543af796f16a4cb54878b86df815)
(cherry picked from commit 705fca7c6398a246bdf2ef00f16cf592a20c6e16)

Resolves: IBMCEPH-14904