mds/QuiesceDbEncoding: add `inline` to work around linker error
Fixes duplicate symbols because every source that includes this header
contains a copy:

 mold: error: duplicate symbol: lib/libceph-common.a(Message.cc.o): lib/libmds.a(MDSRankQuiesce.cc.o): encode(QuiesceDbVersion const&, ceph::buffer::v15_2_0::list&, unsigned long)
 mold: error: duplicate symbol: lib/libceph-common.a(Message.cc.o): lib/libmds.a(MDSRankQuiesce.cc.o): encode(QuiesceState const&, ceph::buffer::v15_2_0::list&, unsigned long)

(and many more)

Signed-off-by: Max Kellermann <max.kellermann@ionos.com>